# Generated by Django 6.0.2 on 2026-05-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('project', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Follow Up', 'Follow Up'), ('Converted', 'Converted'), ('Closed', 'Closed')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='employees.employee')),
            ],
        ),
    ]
