# Generated by Django 6.0.5 on 2026-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
